# Generated by Django 5.2.12 on 2026-06-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pc_builder', '0002_remove_buildhistory_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('brand', models.TextField(null=True)),
                ('price', models.FloatField()),
                ('form', models.TextField(null=True)),
                ('gpu_length', models.IntegerField(null=True)),
                ('air_height', models.IntegerField(null=True)),
                ('water_size', models.CharField(max_length=3, null=True)),
                ('psu_form', models.TextField(null=True)),
                ('storage_2_5', models.IntegerField(null=True)),
                ('storage_3_5', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'case',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('brand', models.TextField(null=True)),
                ('price', models.FloatField()),
                ('socket', models.TextField(null=True)),
                ('core_count', models.IntegerField(null=True)),
                ('thread_count', models.IntegerField(null=True)),
                ('base_clock', models.FloatField(null=True)),
                ('boost_clock', models.FloatField(null=True)),
                ('tdp', models.IntegerField(null=True)),
                ('memory_type', models.TextField(null=True)),
                ('memory_speed', models.IntegerField(null=True)),
                ('single_score', models.FloatField(null=True)),
                ('multi_score', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'cpu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CpuCooler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('brand', models.TextField(null=True)),
                ('price', models.FloatField()),
                ('type', models.TextField(null=True)),
                ('air_height', models.IntegerField(null=True)),
                ('water_size', models.IntegerField(null=True)),
                ('noise_level', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'cpu_cooler',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('chip_brand', models.TextField(null=True)),
                ('card_brand', models.TextField(null=True)),
                ('price', models.FloatField()),
                ('length', models.FloatField(null=True)),
                ('tdp', models.IntegerField(null=True)),
                ('vram_size', models.IntegerField(null=True)),
                ('core_clock', models.FloatField(null=True)),
                ('memory_clock', models.FloatField(null=True)),
                ('gaming_score', models.FloatField(null=True)),
                ('compute_score', models.FloatField(null=True)),
                ('noise_level', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'gpu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('brand', models.TextField(null=True)),
                ('price', models.FloatField()),
                ('form', models.TextField(null=True)),
                ('socket', models.TextField(null=True)),
                ('memory_slots', models.IntegerField(null=True)),
                ('memory_type', models.TextField(null=True)),
                ('memory_frequency', models.IntegerField(null=True)),
                ('m2_slots', models.IntegerField(null=True)),
                ('sata_ports', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'mb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Psu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('brand', models.TextField(null=True)),
                ('price', models.FloatField()),
                ('form', models.TextField(null=True)),
                ('wattage', models.IntegerField(null=True)),
                ('efficiency', models.TextField(null=True)),
            ],
            options={
                'db_table': 'psu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('brand', models.TextField(null=True)),
                ('price', models.FloatField()),
                ('type', models.TextField(null=True)),
                ('capacity', models.IntegerField(null=True)),
                ('frequency', models.IntegerField(null=True)),
                ('latency', models.IntegerField(null=True)),
                ('module_count', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'ram',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('brand', models.TextField(null=True)),
                ('price', models.FloatField()),
                ('type', models.TextField(null=True)),
                ('capacity', models.IntegerField(null=True)),
                ('cache_size', models.IntegerField(null=True)),
                ('read_speed', models.IntegerField(null=True)),
                ('write_speed', models.IntegerField(null=True)),
                ('random_read_iops', models.IntegerField(null=True)),
                ('random_write_iops', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'storage',
                'managed': False,
            },
        ),
    ]
