# Generated by Django 5.2.12 on 2026-03-23 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(choices=[('cpu', 'CPU'), ('gpu', '显卡'), ('mb', '主板'), ('ram', '内存'), ('storage', '存储'), ('psu', '电源'), ('case', '机箱'), ('cooler', '散热器')], max_length=20, verbose_name='配件类型')),
                ('component_id', models.IntegerField(verbose_name='配件 ID')),
                ('features', models.JSONField(default=dict, verbose_name='特征向量')),
                ('gaming_score', models.FloatField(default=0.0, verbose_name='游戏评分')),
                ('office_score', models.FloatField(default=0.0, verbose_name='办公评分')),
                ('productivity_score', models.FloatField(default=0.0, verbose_name='生产力评分')),
                ('efficiency_score', models.FloatField(default=0.0, verbose_name='能效评分')),
                ('value_score', models.FloatField(default=0.0, verbose_name='性价比评分')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'recommender_component_feature',
                'indexes': [models.Index(fields=['component_type'], name='recommender_compone_c3a097_idx'), models.Index(fields=['gaming_score'], name='recommender_gaming__99ebea_idx'), models.Index(fields=['value_score'], name='recommender_value_s_de9f2d_idx')],
                'unique_together': {('component_type', 'component_id')},
            },
        ),
        migrations.CreateModel(
            name='RecommendationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('budget_min', models.FloatField(verbose_name='最低预算')),
                ('budget_max', models.FloatField(verbose_name='最高预算')),
                ('usage', models.CharField(max_length=20, verbose_name='用途')),
                ('cpu_brand', models.CharField(max_length=10, verbose_name='CPU 品牌')),
                ('gpu_brand', models.CharField(max_length=10, verbose_name='显卡品牌')),
                ('priority_mode', models.CharField(default='auto', max_length=20, verbose_name='优先级模式')),
                ('selected_profile', models.CharField(max_length=20, verbose_name='选择的方案')),
                ('total_price', models.FloatField(verbose_name='总价')),
                ('estimated_wattage', models.FloatField(verbose_name='预计功耗')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'recommender_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_cpu_brand', models.CharField(blank=True, max_length=10, verbose_name='偏好 CPU 品牌')),
                ('preferred_gpu_brand', models.CharField(blank=True, max_length=10, verbose_name='偏好显卡品牌')),
                ('performance_priority', models.CharField(choices=[('cpu', 'CPU 优先'), ('gpu', '显卡优先'), ('balanced', '平衡'), ('storage', '存储优先')], default='balanced', max_length=20, verbose_name='性能优先级')),
                ('prefer_rgb', models.BooleanField(default=False, verbose_name='偏好 RGB')),
                ('prefer_silent', models.BooleanField(default=False, verbose_name='偏好静音')),
                ('min_efficiency', models.CharField(blank=True, choices=[('bronze', '铜牌及以上'), ('gold', '金牌及以上'), ('platinum', '白金牌及以上')], max_length=20, verbose_name='最低能效等级')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'recommender_user_preference',
            },
        ),
    ]
