# Generated by Django 5.2.12 on 2026-04-01 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'forum_tag',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('section', models.CharField(choices=[('experience', '经验分享'), ('help', '问题求助'), ('news', '资讯分析')], max_length=20)),
                ('content', models.TextField()),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('favorite_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', '审核中'), ('published', '正常'), ('rejected', '已驳回')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.CharField(blank=True, max_length=255)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_forum_posts', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='forum.forumtag')),
            ],
            options={
                'db_table': 'forum_post',
                'ordering': ('-published_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ForumComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='forum.forumcomment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forum.forumpost')),
            ],
            options={
                'db_table': 'forum_comment',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='ForumUserFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('followee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_followers', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_following', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'forum_user_follow',
            },
        ),
        migrations.CreateModel(
            name='ForumPostFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='forum.forumpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_post_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'forum_post_favorite',
                'constraints': [models.UniqueConstraint(fields=('user', 'post'), name='uniq_forum_favorite_user_post')],
            },
        ),
        migrations.CreateModel(
            name='ForumPostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='forum.forumpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_post_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'forum_post_like',
                'constraints': [models.UniqueConstraint(fields=('user', 'post'), name='uniq_forum_like_user_post')],
            },
        ),
        migrations.AddIndex(
            model_name='forumpost',
            index=models.Index(fields=['section', 'status'], name='forum_post_section_1879e8_idx'),
        ),
        migrations.AddIndex(
            model_name='forumpost',
            index=models.Index(fields=['status', 'published_at'], name='forum_post_status_6b10ec_idx'),
        ),
        migrations.AddIndex(
            model_name='forumpost',
            index=models.Index(fields=['author', 'status'], name='forum_post_author__c92365_idx'),
        ),
        migrations.AddConstraint(
            model_name='forumuserfollow',
            constraint=models.UniqueConstraint(fields=('follower', 'followee'), name='uniq_forum_follow_pair'),
        ),
        migrations.AddConstraint(
            model_name='forumuserfollow',
            constraint=models.CheckConstraint(condition=models.Q(('follower', models.F('followee')), _negated=True), name='chk_forum_no_self_follow'),
        ),
    ]
